
package Vistas;

import Controladores.ControladorGestionPrograma;
import Excepciones.ProgramaNoEncontradoException;
import Excepciones.ProgramaYaRegistradoException;
import Modelo.Programa;
import Util.IList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VistaGestionProgramas extends javax.swing.JFrame {
    
     private ControladorGestionPrograma controladorPrograma;
     
    public VistaGestionProgramas() {
        initComponents();
        setLocationRelativeTo(this);
        controladorPrograma = new ControladorGestionPrograma();
        llenarTablaProgramas();
    }
    
    public void llenarTablaProgramas() {
        IList<Programa> programas = controladorPrograma.getPrograma();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "Nombre", "Codigo", "Facultad", "Semestres"
        });
        for (int i = 0; i < programas.size(); i++) {
            model.addRow(new Object[]{
                programas.get(i).getNombre(),
                programas.get(i).getCodigo(),
                programas.get(i).getFacultad(),
                programas.get(i).getSemestres()
            });
            
        }
        tablaProgramas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblNombrePrograma2 = new javax.swing.JLabel();
        txtNombrePrograma = new javax.swing.JTextField();
        lblCodigoPrograma2 = new javax.swing.JLabel();
        txtCodigoPrograma = new javax.swing.JTextField();
        lblFacultadPrograma2 = new javax.swing.JLabel();
        txtFacultadPrograma = new javax.swing.JTextField();
        lblSemestres2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnAgregarPrograma = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        spSemestresPrograma = new javax.swing.JSpinner();
        btnBuscarPrograma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProgramas = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel13.setBackground(new java.awt.Color(255, 255, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("PROGRAMA"));

        lblNombrePrograma2.setText("Nombre: ");

        lblCodigoPrograma2.setText("Código:");

        lblFacultadPrograma2.setText("Facultad:");

        lblSemestres2.setText("Semestres:");

        jPanel10.setBackground(new java.awt.Color(255, 255, 153));

        btnAgregarPrograma.setBackground(new java.awt.Color(153, 153, 255));
        btnAgregarPrograma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarPrograma.setText("Agregar");
        btnAgregarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProgramaActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(153, 153, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(153, 153, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 51, 51));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiarCampos.setBackground(new java.awt.Color(153, 153, 255));
        btnLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarCampos.setText("Limpiar Campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregarPrograma)
                .addGap(13, 13, 13)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarCampos)
                .addGap(64, 64, 64))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPrograma)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarCampos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBuscarPrograma.setBackground(new java.awt.Color(153, 153, 255));
        btnBuscarPrograma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarPrograma.setText("Buscar");
        btnBuscarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProgramaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblFacultadPrograma2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCodigoPrograma2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombrePrograma2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblSemestres2))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePrograma, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtCodigoPrograma)
                            .addComponent(txtFacultadPrograma)
                            .addComponent(spSemestresPrograma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarPrograma)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoPrograma2)
                    .addComponent(txtCodigoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPrograma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePrograma2)
                    .addComponent(txtNombrePrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFacultadPrograma2)
                    .addComponent(txtFacultadPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSemestres2)
                    .addComponent(spSemestresPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        tablaProgramas.setBackground(new java.awt.Color(255, 255, 153));
        tablaProgramas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Código", "Facultad", "Semestres"
            }
        ));
        jScrollPane1.setViewportView(tablaProgramas);

        btnSalir.setBackground(new java.awt.Color(255, 255, 153));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 255, 153));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnRegresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProgramaActionPerformed
        if (validarCamposTextoProgramas()) {
            try {
                String nombre = txtNombrePrograma.getText();
                String codigo = txtCodigoPrograma.getText();
                String facultad = txtFacultadPrograma.getText();
                int semestres = Integer.parseInt(spSemestresPrograma.getValue().toString());
                Programa programa = new Programa(nombre, codigo, facultad, semestres);
                controladorPrograma.validarPrograma(codigo);
                controladorPrograma.agregarPrograma(programa);
                JOptionPane.showMessageDialog(null, "Programa guardado con exito");
                llenarTablaProgramas();
                limpiarCamposProgramas();
            }catch(ProgramaYaRegistradoException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos de texto o verifique que estén dentro de rangos establecidos");
        }
    }//GEN-LAST:event_btnAgregarProgramaActionPerformed

    private void btnBuscarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProgramaActionPerformed
       String codigo = txtCodigoPrograma.getText();
        if(codigo.isEmpty()){
            JOptionPane.showMessageDialog(null, "Se necesita ingresar el código del programa que desea buscar");
        }else{
            try{
                Programa programaEncontrado = controladorPrograma.buscarPrograma(codigo);
                txtNombrePrograma.setText(programaEncontrado.getNombre());
                txtFacultadPrograma.setText(programaEncontrado.getFacultad());
                spSemestresPrograma.setValue(programaEncontrado.getSemestres());
            }catch(ProgramaNoEncontradoException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } 
    }//GEN-LAST:event_btnBuscarProgramaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String codigo = txtCodigoPrograma.getText();
        if(codigo.isEmpty()){
            JOptionPane.showMessageDialog(null, "Se necesita ingresar el código del perro que desea editar");
        }else{
            if(validarCamposTextoProgramas()){
                try{
                    String nombre = txtNombrePrograma.getText();
                    String facultad = txtFacultadPrograma.getText();
                    int semestres = Integer.parseInt(spSemestresPrograma.getValue().toString());
                    Programa programaActualizado = new Programa(nombre, codigo, facultad, semestres);
                    controladorPrograma.editarPrograma(codigo, programaActualizado);
                    JOptionPane.showMessageDialog(null, "Programa editado con exito");
                    llenarTablaProgramas();
                    limpiarCamposProgramas();
                }catch(ProgramaNoEncontradoException ex){
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtCodigoPrograma.getText();
        if(codigo.isEmpty()){
            JOptionPane.showMessageDialog(null, "Se necesita ingresar el código del programa que desea eliminar");
        }else{
            try{
                controladorPrograma.eliminarPrograma(codigo);
                JOptionPane.showMessageDialog(null, "Programa eliminado con éxito");
                llenarTablaProgramas();
                limpiarCamposProgramas();
            }catch(ProgramaNoEncontradoException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
       limpiarCamposProgramas();
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaAdministrativo vistaAdministrativo = new VistaAdministrativo();
        vistaAdministrativo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       System.exit(0); 
    }//GEN-LAST:event_btnSalirActionPerformed

    
    public boolean validarCamposTextoProgramas(){
        String nombre = txtNombrePrograma.getText();
        String codigo = txtCodigoPrograma.getText();
        String facultad = txtFacultadPrograma.getText();
        int semestres = Integer.parseInt(spSemestresPrograma.getValue().toString());
        if(nombre.isEmpty() || codigo.isEmpty() || facultad.isEmpty()|| semestres <= 0){
            return false;
        }
        return true;
    }
    
    public void limpiarCamposProgramas(){
        txtNombrePrograma.setText("");
        txtCodigoPrograma.setText("");
        txtFacultadPrograma.setText("");
        spSemestresPrograma.setValue(0);
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VistaGestionProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VistaGestionProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VistaGestionProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VistaGestionProgramas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VistaGestionProgramas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPrograma;
    private javax.swing.JButton btnBuscarPrograma;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoPrograma2;
    private javax.swing.JLabel lblFacultadPrograma2;
    private javax.swing.JLabel lblNombrePrograma2;
    private javax.swing.JLabel lblSemestres2;
    private javax.swing.JSpinner spSemestresPrograma;
    private javax.swing.JTable tablaProgramas;
    private javax.swing.JTextField txtCodigoPrograma;
    private javax.swing.JTextField txtFacultadPrograma;
    private javax.swing.JTextField txtNombrePrograma;
    // End of variables declaration//GEN-END:variables
}
